let products = [
  {
    specifications: "Оверсайз",
    price: 999,
    number: 1,
    way: "6.jpg",
    gender: "men",
    key: 6,
    name: "футболка",
    category: "tShirts",
    quantity: 1,
    sizes: ["S", "M", "L", "XL"],
    colors: ["black", "silver", "pink", "red", "orange"],
  },
  {
    specifications: "С принтом",
    price: 1111,
    number: 2,
    way: "6.jpg",
    gender: "men",
    key: 6,
    name: "футболка",
    category: "tShirts",
    quantity: 1,
    sizes: ["S", "M", "L", "XL"],
    colors: ["black", "silver", "pink", "red", "orange"],
  },
  {
    specifications: "Майка",
    price: 1500,
    number: 3,
    way: "6.jpg",
    gender: "men",
    key: 6,
    name: "футболка",
    category: "tShirts",
    quantity: 1,
    sizes: ["S", "M", "L", "XL"],
    colors: ["black", "silver", "pink", "red", "orange"],
  },
  {
    specifications: "Из хлопка",
    price: 1200,
    number: 4,
    way: "6.jpg",
    gender: "men",
    key: 6,
    name: "футболка",
    category: "tShirts",
    quantity: 1,
    sizes: ["S", "M", "L", "XL"],
    colors: ["black", "silver", "pink", "red", "orange"],
  },
  {
    specifications: "Укороченная",
    price: 1149,
    number: 5,
    way: "6.jpg",
    gender: "men",
    key: 6,
    name: "футболка",
    category: "tShirts",
    quantity: 1,
    sizes: ["S", "M", "L", "XL"],
    colors: ["black", "silver", "pink", "red", "orange"],
  },
  {
    specifications: "Оверсайз",
    price: 312,
    number: 6,
    way: "66.jpg",
    gender: "women",
    key: 6,
    name: "футболка",
    category: "tShirts",
    quantity: 1,
    sizes: ["S", "M", "L", "XL"],
    colors: ["black", "silver", "pink", "red", "orange"],
  },
  {
    specifications: "С принтом",
    price: 4323,
    number: 7,
    way: "66.jpg",
    gender: "women",
    key: 6,
    name: "футболка",
    category: "tShirts",
    quantity: 1,
    sizes: ["S", "M", "L", "XL"],
    colors: ["black", "silver", "pink", "red", "orange"],
  },
  {
    specifications: "Майка",
    price: 3243,
    number: 8,
    way: "66.jpg",
    gender: "women",
    key: 6,
    name: "футболка",
    category: "tShirts",
    quantity: 1,
    sizes: ["S", "M", "L", "XL"],
    colors: ["black", "silver", "pink", "red", "orange"],
  },
  {
    specifications: "Из хлопка",
    price: 4322,
    number: 9,
    way: "66.jpg",
    gender: "women",
    key: 6,
    name: "футболка",
    category: "tShirts",
    quantity: 1,
    sizes: ["S", "M", "L", "XL"],
    colors: ["black", "silver", "pink", "red", "orange"],
  },
  {
    specifications: "Укороченная",
    price: 1113,
    number: 10,
    way: "66.jpg",
    gender: "women",
    key: 6,
    name: "футболка",
    category: "tShirts",
    quantity: 1,
    sizes: ["S", "M", "L", "XL"],
    colors: ["black", "silver", "pink", "red", "orange"],
  },
  {
    specifications: "Оверсайз",
    price: 999,
    number: 61,
    way: "6.jpg",
    gender: "men",
    key: 6,
    name: "футболка",
    category: "tShirts",
    quantity: 1,
    sizes: ["S", "M", "L", "XL"],
    colors: ["black", "silver", "pink", "red", "orange"],
  },
  {
    specifications: "С принтом",
    price: 1111,
    number: 62,
    way: "6.jpg",
    gender: "men",
    key: 6,
    name: "футболка",
    category: "tShirts",
    quantity: 1,
    sizes: ["S", "M", "L", "XL"],
    colors: ["black", "silver", "pink", "red", "orange"],
  },
  {
    specifications: "Майка",
    price: 1500,
    number: 63,
    way: "6.jpg",
    gender: "men",
    key: 6,
    name: "футболка",
    category: "tShirts",
    quantity: 1,
    sizes: ["S", "M", "L", "XL"],
    colors: ["black", "silver", "pink", "red", "orange"],
  },
  {
    specifications: "Из хлопка",
    price: 1200,
    number: 64,
    way: "6.jpg",
    gender: "men",
    key: 6,
    name: "футболка",
    category: "tShirts",
    quantity: 1,
    sizes: ["S", "M", "L", "XL"],
    colors: ["black", "silver", "pink", "red", "orange"],
  },
  {
    specifications: "Укороченная",
    price: 1149,
    number: 65,
    way: "6.jpg",
    gender: "men",
    key: 6,
    name: "футболка",
    category: "tShirts",
    quantity: 1,
    sizes: ["S", "M", "L", "XL"],
    colors: ["black", "silver", "pink", "red", "orange"],
  },
  {
    specifications: "Оверсайз",
    price: 312,
    number: 66,
    way: "66.jpg",
    gender: "women",
    key: 6,
    name: "футболка",
    category: "tShirts",
    quantity: 1,
    sizes: ["S", "M", "L", "XL"],
    colors: ["black", "silver", "pink", "red", "orange"],
  },
  {
    specifications: "С принтом",
    price: 4323,
    number: 67,
    way: "66.jpg",
    gender: "women",
    key: 6,
    name: "футболка",
    category: "tShirts",
    quantity: 1,
    sizes: ["S", "M", "L", "XL"],
    colors: ["black", "silver", "pink", "red", "orange"],
  },
  {
    specifications: "Майка",
    price: 3243,
    number: 68,
    way: "66.jpg",
    gender: "women",
    key: 6,
    name: "футболка",
    category: "tShirts",
    quantity: 1,
    sizes: ["S", "M", "L", "XL"],
    colors: ["black", "silver", "pink", "red", "orange"],
  },
  {
    specifications: "Из хлопка",
    price: 4322,
    number: 69,
    way: "66.jpg",
    gender: "women",
    key: 6,
    name: "футболка",
    category: "tShirts",
    quantity: 1,
    sizes: ["S", "M", "L", "XL"],
    colors: ["black", "silver", "pink", "red", "orange"],
  },
  {
    specifications: "Укороченная",
    price: 1113,
    number: 70,
    way: "66.jpg",
    gender: "women",
    key: 6,
    name: "футболка",
    category: "tShirts",
    quantity: 1,
    sizes: ["S", "M", "L", "XL"],
    colors: ["black", "silver", "pink", "red", "orange"],
  },

  {
    specifications: "Укороченные",
    price: 1113,
    number: 11,
    way: "5.jpg",
    gender: "men",
    key: 5,
    name: "брюки",
    category: "trousers",
    quantity: 1,
    sizes: ["S", "M", "L", "XL"],
    colors: ["black", "silver", "pink", "red", "orange"],
  },
  {
    specifications: "Широкие",
    price: 1114,
    number: 12,
    way: "5.jpg",
    gender: "men",
    key: 5,
    name: "брюки",
    category: "trousers",
    quantity: 1,
    sizes: ["S", "M", "L", "XL"],
    colors: ["black", "silver", "pink", "red", "orange"],
  },
  {
    specifications: "Карго",
    price: 2433,
    number: 13,
    way: "5.jpg",
    gender: "men",
    key: 5,
    name: "брюки",
    category: "trousers",
    quantity: 1,
    sizes: ["S", "M", "L", "XL"],
    colors: ["black", "silver", "pink", "red", "orange"],
  },
  {
    specifications: "Спортивные",
    price: 2343,
    number: 14,
    way: "5.jpg",
    gender: "men",
    key: 5,
    name: "брюки",
    category: "trousers",
    quantity: 1,
    sizes: ["S", "M", "L", "XL"],
    colors: ["black", "silver", "pink", "red", "orange"],
  },
  {
    specifications: "Из хлопка",
    price: 3243,
    number: 15,
    way: "5.jpg",
    gender: "men",
    key: 5,
    name: "брюки",
    category: "trousers",
    quantity: 1,
    sizes: ["S", "M", "L", "XL"],
    colors: ["black", "silver", "pink", "red", "orange"],
  },
  {
    specifications: "Из хлопка",
    price: 2344,
    number: 16,
    way: "55.jpg",
    gender: "women",
    key: 5,
    name: "брюки",
    category: "trousers",
    quantity: 1,
    sizes: ["S", "M", "L", "XL"],
    colors: ["black", "silver", "pink", "red", "orange"],
  },
  {
    specifications: "Спортивные",
    price: 3243,
    number: 17,
    way: "55.jpg",
    gender: "women",
    key: 5,
    name: "брюки",
    category: "trousers",
    quantity: 1,
    sizes: ["S", "M", "L", "XL"],
    colors: ["black", "silver", "pink", "red", "orange"],
  },
  {
    specifications: "Карго",
    price: 1212,
    number: 18,
    way: "55.jpg",
    gender: "women",
    key: 5,
    name: "брюки",
    category: "trousers",
    quantity: 1,
    sizes: ["S", "M", "L", "XL"],
    colors: ["black", "silver", "pink", "red", "orange"],
  },
  {
    specifications: "Широкие",
    price: 3211,
    number: 19,
    way: "55.jpg",
    gender: "women",
    key: 5,
    name: "брюки",
    category: "trousers",
    quantity: 1,
    sizes: ["S", "M", "L", "XL"],
    colors: ["black", "silver", "pink", "red", "orange"],
  },
  {
    specifications: "Укороченные",
    price: 1233,
    number: 20,
    way: "55.jpg",
    gender: "women",
    key: 5,
    name: "брюки",
    category: "trousers",
    quantity: 1,
    sizes: ["S", "M", "L", "XL"],
    colors: ["black", "silver", "pink", "red", "orange"],
  },
  {
    specifications: "Укороченные",
    price: 1113,
    number: 71,
    way: "5.jpg",
    gender: "men",
    key: 5,
    name: "брюки",
    category: "trousers",
    quantity: 1,
    sizes: ["S", "M", "L", "XL"],
    colors: ["black", "silver", "pink", "red", "orange"],
  },
  {
    specifications: "Широкие",
    price: 1114,
    number: 72,
    way: "5.jpg",
    gender: "men",
    key: 5,
    name: "брюки",
    category: "trousers",
    quantity: 1,
    sizes: ["S", "M", "L", "XL"],
    colors: ["black", "silver", "pink", "red", "orange"],
  },
  {
    specifications: "Карго",
    price: 2433,
    number: 73,
    way: "5.jpg",
    gender: "men",
    key: 5,
    name: "брюки",
    category: "trousers",
    quantity: 1,
    sizes: ["S", "M", "L", "XL"],
    colors: ["black", "silver", "pink", "red", "orange"],
  },
  {
    specifications: "Спортивные",
    price: 2343,
    number: 74,
    way: "5.jpg",
    gender: "men",
    key: 5,
    name: "брюки",
    category: "trousers",
    quantity: 1,
    sizes: ["S", "M", "L", "XL"],
    colors: ["black", "silver", "pink", "red", "orange"],
  },
  {
    specifications: "Из хлопка",
    price: 3243,
    number: 75,
    way: "5.jpg",
    gender: "men",
    key: 5,
    name: "брюки",
    category: "trousers",
    quantity: 1,
    sizes: ["S", "M", "L", "XL"],
    colors: ["black", "silver", "pink", "red", "orange"],
  },
  {
    specifications: "Из хлопка",
    price: 2344,
    number: 76,
    way: "55.jpg",
    gender: "women",
    key: 5,
    name: "брюки",
    category: "trousers",
    quantity: 1,
    sizes: ["S", "M", "L", "XL"],
    colors: ["black", "silver", "pink", "red", "orange"],
  },
  {
    specifications: "Спортивные",
    price: 3243,
    number: 77,
    way: "55.jpg",
    gender: "women",
    key: 5,
    name: "брюки",
    category: "trousers",
    quantity: 1,
    sizes: ["S", "M", "L", "XL"],
    colors: ["black", "silver", "pink", "red", "orange"],
  },
  {
    specifications: "Карго",
    price: 1212,
    number: 78,
    way: "55.jpg",
    gender: "women",
    key: 5,
    name: "брюки",
    category: "trousers",
    quantity: 1,
    sizes: ["S", "M", "L", "XL"],
    colors: ["black", "silver", "pink", "red", "orange"],
  },
  {
    specifications: "Широкие",
    price: 3211,
    number: 79,
    way: "55.jpg",
    gender: "women",
    key: 5,
    name: "брюки",
    category: "trousers",
    quantity: 1,
    sizes: ["S", "M", "L", "XL"],
    colors: ["black", "silver", "pink", "red", "orange"],
  },
  {
    specifications: "Укороченные",
    price: 1233,
    number: 80,
    way: "55.jpg",
    gender: "women",
    key: 5,
    name: "брюки",
    category: "trousers",
    quantity: 1,
    sizes: ["S", "M", "L", "XL"],
    colors: ["black", "silver", "pink", "red", "orange"],
  },

  {
    specifications: "Анарак",
    price: 3123,
    number: 21,
    way: "4.jpg",
    gender: "men",
    key: 4,
    name: "кофта",
    category: "sweatshirts",
    quantity: 1,
    sizes: ["S", "M", "L", "XL"],
    colors: ["black", "silver", "pink", "red", "orange"],
  },
  {
    specifications: "Кенгуру",
    price: 2132,
    number: 22,
    way: "4.jpg",
    gender: "men",
    key: 4,
    name: "кофта",
    category: "sweatshirts",
    quantity: 1,
    sizes: ["S", "M", "L", "XL"],
    colors: ["black", "silver", "pink", "red", "orange"],
  },
  {
    specifications: "На молнии",
    price: 2132,
    number: 23,
    way: "4.jpg",
    gender: "men",
    key: 4,
    name: "кофта",
    category: "sweatshirts",
    quantity: 1,
    sizes: ["S", "M", "L", "XL"],
    colors: ["black", "silver", "pink", "red", "orange"],
  },
  {
    specifications: "С вышивкой",
    price: 1232,
    number: 24,
    way: "4.jpg",
    gender: "men",
    key: 4,
    name: "кофта",
    category: "sweatshirts",
    quantity: 1,
    sizes: ["S", "M", "L", "XL"],
    colors: ["black", "silver", "pink", "red", "orange"],
  },
  {
    specifications: "В полоску",
    price: 1232,
    number: 25,
    way: "4.jpg",
    gender: "men",
    key: 4,
    name: "кофта",
    category: "sweatshirts",
    quantity: 1,
    sizes: ["S", "M", "L", "XL"],
    colors: ["black", "silver", "pink", "red", "orange"],
  },
  {
    specifications: "В полоску",
    price: 2133,
    number: 26,
    way: "44.jpg",
    gender: "women",
    key: 4,
    name: "кофта",
    category: "sweatshirts",
    quantity: 1,
    sizes: ["S", "M", "L", "XL"],
    colors: ["black", "silver", "pink", "red", "orange"],
  },
  {
    specifications: "С вышивкой",
    price: 2133,
    number: 27,
    way: "44.jpg",
    gender: "women",
    key: 4,
    name: "кофта",
    category: "sweatshirts",
    quantity: 1,
    sizes: ["S", "M", "L", "XL"],
    colors: ["black", "silver", "pink", "red", "orange"],
  },
  {
    specifications: "На молнии",
    price: 1233,
    number: 28,
    way: "44.jpg",
    gender: "women",
    key: 4,
    name: "кофта",
    category: "sweatshirts",
    quantity: 1,
    sizes: ["S", "M", "L", "XL"],
    colors: ["black", "silver", "pink", "red", "orange"],
  },
  {
    specifications: "Кенгуру",
    price: 3443,
    number: 29,
    way: "44.jpg",
    gender: "women",
    key: 4,
    name: "кофта",
    category: "sweatshirts",
    quantity: 1,
    sizes: ["S", "M", "L", "XL"],
    colors: ["black", "silver", "pink", "red", "orange"],
  },
  {
    specifications: "Анарак",
    price: 3243,
    number: 30,
    way: "44.jpg",
    gender: "women",
    key: 4,
    name: "кофта",
    category: "sweatshirts",
    quantity: 1,
    sizes: ["S", "M", "L", "XL"],
    colors: ["black", "silver", "pink", "red", "orange"],
  },
  {
    specifications: "Анарак",
    price: 3123,
    number: 81,
    way: "4.jpg",
    gender: "men",
    key: 4,
    name: "кофта",
    category: "sweatshirts",
    quantity: 1,
    sizes: ["S", "M", "L", "XL"],
    colors: ["black", "silver", "pink", "red", "orange"],
  },
  {
    specifications: "Кенгуру",
    price: 2132,
    number: 82,
    way: "4.jpg",
    gender: "men",
    key: 4,
    name: "кофта",
    category: "sweatshirts",
    quantity: 1,
    sizes: ["S", "M", "L", "XL"],
    colors: ["black", "silver", "pink", "red", "orange"],
  },
  {
    specifications: "На молнии",
    price: 2132,
    number: 83,
    way: "4.jpg",
    gender: "men",
    key: 4,
    name: "кофта",
    category: "sweatshirts",
    quantity: 1,
    sizes: ["S", "M", "L", "XL"],
    colors: ["black", "silver", "pink", "red", "orange"],
  },
  {
    specifications: "С вышивкой",
    price: 1232,
    number: 84,
    way: "4.jpg",
    gender: "men",
    key: 4,
    name: "кофта",
    category: "sweatshirts",
    quantity: 1,
    sizes: ["S", "M", "L", "XL"],
    colors: ["black", "silver", "pink", "red", "orange"],
  },
  {
    specifications: "В полоску",
    price: 1232,
    number: 85,
    way: "4.jpg",
    gender: "men",
    key: 4,
    name: "кофта",
    category: "sweatshirts",
    quantity: 1,
    sizes: ["S", "M", "L", "XL"],
    colors: ["black", "silver", "pink", "red", "orange"],
  },
  {
    specifications: "В полоску",
    price: 2133,
    number: 86,
    way: "44.jpg",
    gender: "women",
    key: 4,
    name: "кофта",
    category: "sweatshirts",
    quantity: 1,
    sizes: ["S", "M", "L", "XL"],
    colors: ["black", "silver", "pink", "red", "orange"],
  },
  {
    specifications: "С вышивкой",
    price: 2133,
    number: 87,
    way: "44.jpg",
    gender: "women",
    key: 4,
    name: "кофта",
    category: "sweatshirts",
    quantity: 1,
    sizes: ["S", "M", "L", "XL"],
    colors: ["black", "silver", "pink", "red", "orange"],
  },
  {
    specifications: "На молнии",
    price: 1233,
    number: 88,
    way: "44.jpg",
    gender: "women",
    key: 4,
    name: "кофта",
    category: "sweatshirts",
    quantity: 1,
    sizes: ["S", "M", "L", "XL"],
    colors: ["black", "silver", "pink", "red", "orange"],
  },
  {
    specifications: "Кенгуру",
    price: 3443,
    number: 89,
    way: "44.jpg",
    gender: "women",
    key: 4,
    name: "кофта",
    category: "sweatshirts",
    quantity: 1,
    sizes: ["S", "M", "L", "XL"],
    colors: ["black", "silver", "pink", "red", "orange"],
  },
  {
    specifications: "Анарак",
    price: 3243,
    number: 90,
    way: "44.jpg",
    gender: "women",
    key: 4,
    name: "кофта",
    category: "sweatshirts",
    quantity: 1,
    sizes: ["S", "M", "L", "XL"],
    colors: ["black", "silver", "pink", "red", "orange"],
  },

  {
    specifications: "Спортивные",
    price: 3937,
    number: 31,
    way: "3.jpg",
    gender: "men",
    key: 3,
    name: "шорты",
    category: "shorts",
    quantity: 1,
    sizes: ["S", "M", "L", "XL"],
    colors: ["black", "silver", "pink", "red", "orange"],
  },
  {
    specifications: "Пляжные",
    price: 3847,
    number: 32,
    way: "3.jpg",
    gender: "men",
    key: 3,
    name: "шорты",
    category: "shorts",
    quantity: 1,
    sizes: ["S", "M", "L", "XL"],
    colors: ["black", "silver", "pink", "red", "orange"],
  },
  {
    specifications: "Джинсовые",
    price: 3244,
    number: 33,
    way: "3.jpg",
    gender: "men",
    key: 3,
    name: "шорты",
    category: "shorts",
    quantity: 1,
    sizes: ["S", "M", "L", "XL"],
    colors: ["black", "silver", "pink", "red", "orange"],
  },
  {
    specifications: "Удлиненные",
    price: 1113,
    number: 34,
    way: "3.jpg",
    gender: "men",
    key: 3,
    name: "шорты",
    category: "shorts",
    quantity: 1,
    sizes: ["S", "M", "L", "XL"],
    colors: ["black", "silver", "pink", "red", "orange"],
  },
  {
    specifications: "Хлопковые",
    price: 1115,
    number: 35,
    way: "3.jpg",
    gender: "men",
    key: 3,
    name: "шорты",
    category: "shorts",
    quantity: 1,
    sizes: ["S", "M", "L", "XL"],
    colors: ["black", "silver", "pink", "red", "orange"],
  },
  {
    specifications: "Хлопковые",
    price: 1114,
    number: 36,
    way: "33.jpg",
    gender: "women",
    key: 3,
    name: "шорты",
    category: "shorts",
    quantity: 1,
    sizes: ["S", "M", "L", "XL"],
    colors: ["black", "silver", "pink", "red", "orange"],
  },
  {
    specifications: "Удлиненные",
    price: 1113,
    number: 37,
    way: "33.jpg",
    gender: "women",
    key: 3,
    name: "шорты",
    category: "shorts",
    quantity: 1,
    sizes: ["S", "M", "L", "XL"],
    colors: ["black", "silver", "pink", "red", "orange"],
  },
  {
    specifications: "Джинсовые",
    price: 1115,
    number: 38,
    way: "33.jpg",
    gender: "women",
    key: 3,
    name: "шорты",
    category: "shorts",
    quantity: 1,
    sizes: ["S", "M", "L", "XL"],
    colors: ["black", "silver", "pink", "red", "orange"],
  },
  {
    specifications: "Пляжные",
    price: 1123,
    number: 39,
    way: "33.jpg",
    gender: "women",
    key: 3,
    name: "шорты",
    category: "shorts",
    quantity: 1,
    sizes: ["S", "M", "L", "XL"],
    colors: ["black", "silver", "pink", "red", "orange"],
  },
  {
    specifications: "Спортивные",
    price: 1321,
    number: 40,
    way: "33.jpg",
    gender: "women",
    key: 3,
    name: "шорты",
    category: "shorts",
    quantity: 1,
    sizes: ["S", "M", "L", "XL"],
    colors: ["black", "silver", "pink", "red", "orange"],
  },
  {
    specifications: "Спортивные",
    price: 3937,
    number: 91,
    way: "3.jpg",
    gender: "men",
    key: 3,
    name: "шорты",
    category: "shorts",
    quantity: 1,
    sizes: ["S", "M", "L", "XL"],
    colors: ["black", "silver", "pink", "red", "orange"],
  },
  {
    specifications: "Пляжные",
    price: 3847,
    number: 92,
    way: "3.jpg",
    gender: "men",
    key: 3,
    name: "шорты",
    category: "shorts",
    quantity: 1,
    sizes: ["S", "M", "L", "XL"],
    colors: ["black", "silver", "pink", "red", "orange"],
  },
  {
    specifications: "Джинсовые",
    price: 3244,
    number: 93,
    way: "3.jpg",
    gender: "men",
    key: 3,
    name: "шорты",
    category: "shorts",
    quantity: 1,
    sizes: ["S", "M", "L", "XL"],
    colors: ["black", "silver", "pink", "red", "orange"],
  },
  {
    specifications: "Удлиненные",
    price: 1113,
    number: 94,
    way: "3.jpg",
    gender: "men",
    key: 3,
    name: "шорты",
    category: "shorts",
    quantity: 1,
    sizes: ["S", "M", "L", "XL"],
    colors: ["black", "silver", "pink", "red", "orange"],
  },
  {
    specifications: "Хлопковые",
    price: 1115,
    number: 95,
    way: "3.jpg",
    gender: "men",
    key: 3,
    name: "шорты",
    category: "shorts",
    quantity: 1,
    sizes: ["S", "M", "L", "XL"],
    colors: ["black", "silver", "pink", "red", "orange"],
  },
  {
    specifications: "Хлопковые",
    price: 1114,
    number: 96,
    way: "33.jpg",
    gender: "women",
    key: 3,
    name: "шорты",
    category: "shorts",
    quantity: 1,
    sizes: ["S", "M", "L", "XL"],
    colors: ["black", "silver", "pink", "red", "orange"],
  },
  {
    specifications: "Удлиненные",
    price: 1113,
    number: 97,
    way: "33.jpg",
    gender: "women",
    key: 3,
    name: "шорты",
    category: "shorts",
    quantity: 1,
    sizes: ["S", "M", "L", "XL"],
    colors: ["black", "silver", "pink", "red", "orange"],
  },
  {
    specifications: "Джинсовые",
    price: 1115,
    number: 98,
    way: "33.jpg",
    gender: "women",
    key: 3,
    name: "шорты",
    category: "shorts",
    quantity: 1,
    sizes: ["S", "M", "L", "XL"],
    colors: ["black", "silver", "pink", "red", "orange"],
  },
  {
    specifications: "Пляжные",
    price: 1123,
    number: 99,
    way: "33.jpg",
    gender: "women",
    key: 3,
    name: "шорты",
    category: "shorts",
    quantity: 1,
    sizes: ["S", "M", "L", "XL"],
    colors: ["black", "silver", "pink", "red", "orange"],
  },
  {
    specifications: "Спортивные",
    price: 1321,
    number: 100,
    way: "33.jpg",
    gender: "women",
    key: 3,
    name: "шорты",
    category: "shorts",
    quantity: 1,
    sizes: ["S", "M", "L", "XL"],
    colors: ["black", "silver", "pink", "red", "orange"],
  },

  {
    specifications: "С капюшоном",
    price: 3111,
    number: 41,
    way: "2.jpg",
    gender: "men",
    key: 2,
    name: "куртка",
    category: "jackets",
    quantity: 1,
    sizes: ["S", "M", "L", "XL"],
    colors: ["black", "silver", "pink", "red", "orange"],
  },
  {
    specifications: "Зимняя",
    price: 3111,
    number: 42,
    way: "2.jpg",
    gender: "men",
    key: 2,
    name: "куртка",
    category: "jackets",
    quantity: 1,
    sizes: ["S", "M", "L", "XL"],
    colors: ["black", "silver", "pink", "red", "orange"],
  },
  {
    specifications: "Ветровка",
    price: 1121,
    number: 43,
    way: "2.jpg",
    gender: "men",
    key: 2,
    name: "куртка",
    category: "jackets",
    quantity: 1,
    sizes: ["S", "M", "L", "XL"],
    colors: ["black", "silver", "pink", "red", "orange"],
  },
  {
    specifications: "Пальто",
    price: 1141,
    number: 44,
    way: "2.jpg",
    gender: "men",
    key: 2,
    name: "куртка",
    category: "jackets",
    quantity: 1,
    sizes: ["S", "M", "L", "XL"],
    colors: ["black", "silver", "pink", "red", "orange"],
  },
  {
    specifications: "Плащ",
    price: 1411,
    number: 45,
    way: "2.jpg",
    gender: "men",
    key: 2,
    name: "куртка",
    category: "jackets",
    quantity: 1,
    sizes: ["S", "M", "L", "XL"],
    colors: ["black", "silver", "pink", "red", "orange"],
  },
  {
    specifications: "Плащ",
    price: 1151,
    number: 46,
    way: "22.jpg",
    gender: "women",
    key: 2,
    name: "куртка",
    category: "jackets",
    quantity: 1,
    sizes: ["S", "M", "L", "XL"],
    colors: ["black", "silver", "pink", "red", "orange"],
  },
  {
    specifications: "Пальто",
    price: 1119,
    number: 47,
    way: "22.jpg",
    gender: "women",
    key: 2,
    name: "куртка",
    category: "jackets",
    quantity: 1,
    sizes: ["S", "M", "L", "XL"],
    colors: ["black", "silver", "pink", "red", "orange"],
  },
  {
    specifications: "Ветровка",
    price: 1113,
    number: 48,
    way: "22.jpg",
    gender: "women",
    key: 2,
    name: "куртка",
    category: "jackets",
    quantity: 1,
    sizes: ["S", "M", "L", "XL"],
    colors: ["black", "silver", "pink", "red", "orange"],
  },
  {
    specifications: "Зимняя",
    price: 1115,
    number: 49,
    way: "22.jpg",
    gender: "women",
    key: 2,
    name: "куртка",
    category: "jackets",
    quantity: 1,
    sizes: ["S", "M", "L", "XL"],
    colors: ["black", "silver", "pink", "red", "orange"],
  },
  {
    specifications: "С капюшоном",
    price: 1116,
    number: 50,
    way: "22.jpg",
    gender: "women",
    key: 2,
    name: "куртка",
    category: "jackets",
    quantity: 1,
    sizes: ["S", "M", "L", "XL"],
    colors: ["black", "silver", "pink", "red", "orange"],
  },
  {
    specifications: "С капюшоном",
    price: 3111,
    number: 101,
    way: "2.jpg",
    gender: "men",
    key: 2,
    name: "куртка",
    category: "jackets",
    quantity: 1,
    sizes: ["S", "M", "L", "XL"],
    colors: ["black", "silver", "pink", "red", "orange"],
  },
  {
    specifications: "Зимняя",
    price: 3111,
    number: 102,
    way: "2.jpg",
    gender: "men",
    key: 2,
    name: "куртка",
    category: "jackets",
    quantity: 1,
    sizes: ["S", "M", "L", "XL"],
    colors: ["black", "silver", "pink", "red", "orange"],
  },
  {
    specifications: "Ветровка",
    price: 1121,
    number: 103,
    way: "2.jpg",
    gender: "men",
    key: 2,
    name: "куртка",
    category: "jackets",
    quantity: 1,
    sizes: ["S", "M", "L", "XL"],
    colors: ["black", "silver", "pink", "red", "orange"],
  },
  {
    specifications: "Пальто",
    price: 1141,
    number: 104,
    way: "2.jpg",
    gender: "men",
    key: 2,
    name: "куртка",
    category: "jackets",
    quantity: 1,
    sizes: ["S", "M", "L", "XL"],
    colors: ["black", "silver", "pink", "red", "orange"],
  },
  {
    specifications: "Плащ",
    price: 1411,
    number: 105,
    way: "2.jpg",
    gender: "men",
    key: 2,
    name: "куртка",
    category: "jackets",
    quantity: 1,
    sizes: ["S", "M", "L", "XL"],
    colors: ["black", "silver", "pink", "red", "orange"],
  },
  {
    specifications: "Плащ",
    price: 1151,
    number: 106,
    way: "22.jpg",
    gender: "women",
    key: 2,
    name: "куртка",
    category: "jackets",
    quantity: 1,
    sizes: ["S", "M", "L", "XL"],
    colors: ["black", "silver", "pink", "red", "orange"],
  },
  {
    specifications: "Пальто",
    price: 1119,
    number: 107,
    way: "22.jpg",
    gender: "women",
    key: 2,
    name: "куртка",
    category: "jackets",
    quantity: 1,
    sizes: ["S", "M", "L", "XL"],
    colors: ["black", "silver", "pink", "red", "orange"],
  },
  {
    specifications: "Ветровка",
    price: 1113,
    number: 108,
    way: "22.jpg",
    gender: "women",
    key: 2,
    name: "куртка",
    category: "jackets",
    quantity: 1,
    sizes: ["S", "M", "L", "XL"],
    colors: ["black", "silver", "pink", "red", "orange"],
  },
  {
    specifications: "Зимняя",
    price: 1115,
    number: 109,
    way: "22.jpg",
    gender: "women",
    key: 2,
    name: "куртка",
    category: "jackets",
    quantity: 1,
    sizes: ["S", "M", "L", "XL"],
    colors: ["black", "silver", "pink", "red", "orange"],
  },
  {
    specifications: "С капюшоном",
    price: 1116,
    number: 110,
    way: "22.jpg",
    gender: "women",
    key: 2,
    name: "куртка",
    category: "jackets",
    quantity: 1,
    sizes: ["S", "M", "L", "XL"],
    colors: ["black", "silver", "pink", "red", "orange"],
  },

  {
    specifications: "Стрейч",
    price: 1113,
    number: 51,
    way: "1.jpg",
    gender: "men",
    key: 1,
    name: "джинсы",
    category: "hits",
    quantity: 1,
    sizes: ["S", "M", "L", "XL"],
    colors: ["black", "silver", "pink", "red", "orange"],
  },
  {
    specifications: "Скинни",
    price: 3111,
    number: 52,
    way: "1.jpg",
    gender: "men",
    key: 1,
    name: "джинсы",
    category: "hits",
    quantity: 1,
    sizes: ["S", "M", "L", "XL"],
    colors: ["black", "silver", "pink", "red", "orange"],
  },
  {
    specifications: "Слим",
    price: 3111,
    number: 53,
    way: "1.jpg",
    gender: "men",
    key: 1,
    name: "джинсы",
    category: "hits",
    quantity: 1,
    sizes: ["S", "M", "L", "XL"],
    colors: ["black", "silver", "pink", "red", "orange"],
  },
  {
    specifications: "Бананы",
    price: 4111,
    number: 54,
    way: "1.jpg",
    gender: "men",
    key: 1,
    name: "джинсы",
    category: "hits",
    quantity: 1,
    sizes: ["S", "M", "L", "XL"],
    colors: ["black", "silver", "pink", "red", "orange"],
  },
  {
    specifications: "Трубы",
    price: 6111,
    number: 55,
    way: "1.jpg",
    gender: "men",
    key: 1,
    name: "джинсы",
    category: "hits",
    quantity: 1,
    sizes: ["S", "M", "L", "XL"],
    colors: ["black", "silver", "pink", "red", "orange"],
  },
  {
    specifications: "Трубы",
    price: 7111,
    number: 56,
    way: "11.jpg",
    gender: "women",
    key: 1,
    name: "джинсы",
    category: "hits",
    quantity: 1,
    sizes: ["S", "M", "L", "XL"],
    colors: ["black", "silver", "pink", "red", "orange"],
  },
  {
    specifications: "Бананы",
    price: 2111,
    number: 57,
    way: "11.jpg",
    gender: "women",
    key: 1,
    name: "джинсы",
    category: "hits",
    quantity: 1,
    sizes: ["S", "M", "L", "XL"],
    colors: ["black", "silver", "pink", "red", "orange"],
  },
  {
    specifications: "Слим",
    price: 1311,
    number: 58,
    way: "11.jpg",
    gender: "women",
    key: 1,
    name: "джинсы",
    category: "hits",
    quantity: 1,
    sizes: ["S", "M", "L", "XL"],
    colors: ["black", "silver", "pink", "red", "orange"],
  },
  {
    specifications: "Скинни",
    price: 1311,
    number: 59,
    way: "11.jpg",
    gender: "women",
    key: 1,
    name: "джинсы",
    category: "hits",
    quantity: 1,
    sizes: ["S", "M", "L", "XL"],
    colors: ["black", "silver", "pink", "red", "orange"],
  },
  {
    specifications: "Стрейч",
    price: 1211,
    number: 60,
    way: "11.jpg",
    gender: "women",
    key: 1,
    name: "джинсы",
    category: "hits",
    quantity: 1,
    sizes: ["S", "M", "L", "XL"],
    colors: ["black", "silver", "pink", "red", "orange"],
  },
  {
    specifications: "Стрейч",
    price: 1113,
    number: 111,
    way: "1.jpg",
    gender: "men",
    key: 1,
    name: "джинсы",
    category: "hits",
    quantity: 1,
    sizes: ["S", "M", "L", "XL"],
    colors: ["black", "silver", "pink", "red", "orange"],
  },
  {
    specifications: "Скинни",
    price: 3111,
    number: 112,
    way: "1.jpg",
    gender: "men",
    key: 1,
    name: "джинсы",
    category: "hits",
    quantity: 1,
    sizes: ["S", "M", "L", "XL"],
    colors: ["black", "silver", "pink", "red", "orange"],
  },
  {
    specifications: "Слим",
    price: 3111,
    number: 113,
    way: "1.jpg",
    gender: "men",
    key: 1,
    name: "джинсы",
    category: "hits",
    quantity: 1,
    sizes: ["S", "M", "L", "XL"],
    colors: ["black", "silver", "pink", "red", "orange"],
  },
  {
    specifications: "Бананы",
    price: 4111,
    number: 114,
    way: "1.jpg",
    gender: "men",
    key: 1,
    name: "джинсы",
    category: "hits",
    quantity: 1,
    sizes: ["S", "M", "L", "XL"],
    colors: ["black", "silver", "pink", "red", "orange"],
  },
  {
    specifications: "Трубы",
    price: 6111,
    number: 115,
    way: "1.jpg",
    gender: "men",
    key: 1,
    name: "джинсы",
    category: "hits",
    quantity: 1,
    sizes: ["S", "M", "L", "XL"],
    colors: ["black", "silver", "pink", "red", "orange"],
  },
  {
    specifications: "Трубы",
    price: 7111,
    number: 116,
    way: "11.jpg",
    gender: "women",
    key: 1,
    name: "джинсы",
    category: "hits",
    quantity: 1,
    sizes: ["S", "M", "L", "XL"],
    colors: ["black", "silver", "pink", "red", "orange"],
  },
  {
    specifications: "Бананы",
    price: 2111,
    number: 117,
    way: "11.jpg",
    gender: "women",
    key: 1,
    name: "джинсы",
    category: "hits",
    quantity: 1,
    sizes: ["S", "M", "L", "XL"],
    colors: ["black", "silver", "pink", "red", "orange"],
  },
  {
    specifications: "Слим",
    price: 1311,
    number: 118,
    way: "11.jpg",
    gender: "women",
    key: 1,
    name: "джинсы",
    category: "hits",
    quantity: 1,
    sizes: ["S", "M", "L", "XL"],
    colors: ["black", "silver", "pink", "red", "orange"],
  },
  {
    specifications: "Скинни",
    price: 1311,
    number: 119,
    way: "11.jpg",
    gender: "women",
    key: 1,
    name: "джинсы",
    category: "hits",
    quantity: 1,
    sizes: ["S", "M", "L", "XL"],
    colors: ["black", "silver", "pink", "red", "orange"],
  },
  {
    specifications: "Стрейч",
    price: 1211,
    number: 120,
    way: "11.jpg",
    gender: "women",
    key: 1,
    name: "джинсы",
    category: "hits",
    quantity: 1,
    sizes: ["S", "M", "L", "XL"],
    colors: ["black", "silver", "pink", "red", "orange"],
  },
  {
    specifications: "Оверсайз",
    price: 9990,
    number: 121,
    way: "6.jpg",
    gender: "men",
    key: 6,
    name: "футболка",
    category: "tShirts",
    quantity: 1,
    sizes: ["S", "M", "L", "XL"],
    colors: ["black", "silver", "pink", "red", "orange"],
  },
  {
    specifications: "С принтом",
    price: 111,
    number: 122,
    way: "6.jpg",
    gender: "men",
    key: 6,
    name: "футболка",
    category: "tShirts",
    quantity: 1,
    sizes: ["S", "M", "L", "XL"],
    colors: ["black", "silver", "pink", "red", "orange"],
  },
  {
    specifications: "Оверсайз",
    price: 3122,
    number: 123,
    way: "66.jpg",
    gender: "women",
    key: 6,
    name: "футболка",
    category: "tShirts",
    quantity: 1,
    sizes: ["S", "M", "L", "XL"],
    colors: ["black", "silver", "pink", "red", "orange"],
  },
  {
    specifications: "С принтом",
    price: 433,
    number: 124,
    way: "66.jpg",
    gender: "women",
    key: 6,
    name: "футболка",
    category: "tShirts",
    quantity: 1,
    sizes: ["S", "M", "L", "XL"],
    colors: ["black", "silver", "pink", "red", "orange"],
  },
  {
    specifications: "Укороченные",
    price: 1133,
    number: 125,
    way: "5.jpg",
    gender: "men",
    key: 5,
    name: "брюки",
    category: "trousers",
    quantity: 1,
    sizes: ["S", "M", "L", "XL"],
    colors: ["black", "silver", "pink", "red", "orange"],
  },
  {
    specifications: "Широкие",
    price: 1414,
    number: 126,
    way: "5.jpg",
    gender: "men",
    key: 5,
    name: "брюки",
    category: "trousers",
    quantity: 1,
    sizes: ["S", "M", "L", "XL"],
    colors: ["black", "silver", "pink", "red", "orange"],
  },
  {
    specifications: "Карго",
    price: 1112,
    number: 127,
    way: "55.jpg",
    gender: "women",
    key: 5,
    name: "брюки",
    category: "trousers",
    quantity: 1,
    sizes: ["S", "M", "L", "XL"],
    colors: ["black", "silver", "pink", "red", "orange"],
  },
  {
    specifications: "Широкие",
    price: 3311,
    number: 128,
    way: "55.jpg",
    gender: "women",
    key: 5,
    name: "брюки",
    category: "trousers",
    quantity: 1,
    sizes: ["S", "M", "L", "XL"],
    colors: ["black", "silver", "pink", "red", "orange"],
  },
  {
    specifications: "На молнии",
    price: 2932,
    number: 129,
    way: "4.jpg",
    gender: "men",
    key: 4,
    name: "кофта",
    category: "sweatshirts",
    quantity: 1,
    sizes: ["S", "M", "L", "XL"],
    colors: ["black", "silver", "pink", "red", "orange"],
  },
  {
    specifications: "С вышивкой",
    price: 1272,
    number: 130,
    way: "4.jpg",
    gender: "men",
    key: 4,
    name: "кофта",
    category: "sweatshirts",
    quantity: 1,
    sizes: ["S", "M", "L", "XL"],
    colors: ["black", "silver", "pink", "red", "orange"],
  },
  {
    specifications: "Кенгуру",
    price: 3643,
    number: 131,
    way: "44.jpg",
    gender: "women",
    key: 4,
    name: "кофта",
    category: "sweatshirts",
    quantity: 1,
    sizes: ["S", "M", "L", "XL"],
    colors: ["black", "silver", "pink", "red", "orange"],
  },
  {
    specifications: "Анарак",
    price: 3143,
    number: 132,
    way: "44.jpg",
    gender: "women",
    key: 4,
    name: "кофта",
    category: "sweatshirts",
    quantity: 1,
    sizes: ["S", "M", "L", "XL"],
    colors: ["black", "silver", "pink", "red", "orange"],
  },
  {
    specifications: "Удлиненные",
    price: 5113,
    number: 133,
    way: "3.jpg",
    gender: "men",
    key: 3,
    name: "шорты",
    category: "shorts",
    quantity: 1,
    sizes: ["S", "M", "L", "XL"],
    colors: ["black", "silver", "pink", "red", "orange"],
  },
  {
    specifications: "Хлопковые",
    price: 1515,
    number: 134,
    way: "3.jpg",
    gender: "men",
    key: 3,
    name: "шорты",
    category: "shorts",
    quantity: 1,
    sizes: ["S", "M", "L", "XL"],
    colors: ["black", "silver", "pink", "red", "orange"],
  },
  {
    specifications: "Пляжные",
    price: 2123,
    number: 135,
    way: "33.jpg",
    gender: "women",
    key: 3,
    name: "шорты",
    category: "shorts",
    quantity: 1,
    sizes: ["S", "M", "L", "XL"],
    colors: ["black", "silver", "pink", "red", "orange"],
  },
  {
    specifications: "Спортивные",
    price: 1121,
    number: 136,
    way: "33.jpg",
    gender: "women",
    key: 3,
    name: "шорты",
    category: "shorts",
    quantity: 1,
    sizes: ["S", "M", "L", "XL"],
    colors: ["black", "silver", "pink", "red", "orange"],
  },
  {
    specifications: "Пальто",
    price: 4141,
    number: 137,
    way: "2.jpg",
    gender: "men",
    key: 2,
    name: "куртка",
    category: "jackets",
    quantity: 1,
    sizes: ["S", "M", "L", "XL"],
    colors: ["black", "silver", "pink", "red", "orange"],
  },
  {
    specifications: "Плащ",
    price: 2411,
    number: 138,
    way: "2.jpg",
    gender: "men",
    key: 2,
    name: "куртка",
    category: "jackets",
    quantity: 1,
    sizes: ["S", "M", "L", "XL"],
    colors: ["black", "silver", "pink", "red", "orange"],
  },
  {
    specifications: "Плащ",
    price: 2151,
    number: 139,
    way: "22.jpg",
    gender: "women",
    key: 2,
    name: "куртка",
    category: "jackets",
    quantity: 1,
    sizes: ["S", "M", "L", "XL"],
    colors: ["black", "silver", "pink", "red", "orange"],
  },
  {
    specifications: "Пальто",
    price: 4119,
    number: 140,
    way: "22.jpg",
    gender: "women",
    key: 2,
    name: "куртка",
    category: "jackets",
    quantity: 1,
    sizes: ["S", "M", "L", "XL"],
    colors: ["black", "silver", "pink", "red", "orange"],
  },
  {
    specifications: "Скинни",
    price: 2311,
    number: 141,
    way: "11.jpg",
    gender: "women",
    key: 1,
    name: "джинсы",
    category: "hits",
    quantity: 1,
    sizes: ["S", "M", "L", "XL"],
    colors: ["black", "silver", "pink", "red", "orange"],
  },
  {
    specifications: "Стрейч",
    price: 3211,
    number: 142,
    way: "11.jpg",
    gender: "women",
    key: 1,
    name: "джинсы",
    category: "hits",
    quantity: 1,
    sizes: ["S", "M", "L", "XL"],
    colors: ["black", "silver", "pink", "red", "orange"],
  },
  {
    specifications: "Стрейч",
    price: 8113,
    number: 143,
    way: "1.jpg",
    gender: "men",
    key: 1,
    name: "джинсы",
    category: "hits",
    quantity: 1,
    sizes: ["S", "M", "L", "XL"],
    colors: ["black", "silver", "pink", "red", "orange"],
  },
];

export default products;
